<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                version="1.0">
  <xsl:import href="../../../style/xsl-query-2016.xsl"/>

  <!-- Baseline date from which differences will be shown -->
  <xsl:param name="diff.baseline" select="'0001-01-01'"/>

<xsl:param name="additional.css">
<xsl:text>
dd.indent { margin-left: 2em; }
p.element-syntax { border: solid thin; background-color: #ffccff }
div.proto { border: solid thin; background-color: #ffccff }
div.example { border: solid thin; background-color: blue; padding: 1em }
span.verb { font: small-caps 100% sans-serif }
span.error { font-size: small }
</xsl:text>
</xsl:param>

<!-- ==================================================================== -->

<!-- changed templates to auto generate an appendix with a list
     of links to open issues. -->
<xsl:template name="autogenerated-appendices-toc"/>

<xsl:template name="autogenerated-appendices"/>

  <xsl:template match="processing-instruction('schema-for-params')">
    <pre>
      <xsl:sequence
         select="unparsed-text('../src/schema-for-serialization-parameters.xsd')"/>
    </pre>
  </xsl:template>

</xsl:stylesheet>

