/* Generated By:JJTree: Do not edit this line. C:/proj/xqed2/grammar/parser/xquery-src\XPathVisitor.java */

public interface XPathVisitor
{
  public Object visit(SimpleNode node, Object data);
}
